"""add wallet table

Revision ID: 008e3be8bc24
Revises: 
Create Date: 2022-10-07 23:16:48.553249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008e3be8bc24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('private_key', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    # ### end Alembic commands ###
